//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBox.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevBoxEntities : DbContext
    {
        public DevBoxEntities()
            : base("name=DevBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Complies_Puzzle_Question> Complies_Puzzle_Question { get; set; }
        public virtual DbSet<Puzzle> Puzzle { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Tips> Tips { get; set; }
    }
}
